feat: $addToSet
SamVerschueren/dynongo pull request #78
Opened 2020-10-22 22:05 UTC by onhate

2020-10-26 13:42 UTC, onhate commented
@SamVerschueren let me know your thoughts, specially the $removeFromSet comment.

2020-10-28 07:25 UTC, SamVerschueren requested changes
This is very nice work @onhate! Thanks for adding this 🙏 !

I have one nitpick comment (see review) and maybe a question which I didn't see in the tests. What happens if you do a `{$addToSet: {friends: ['mario', 'luigi']}}`? Will it just add the array as is to the set?

Maybe also add an example of the `$addToSet` to the [Update section](https://github.com/SamVerschueren/dynongo#update).

2020-10-28 07:25 UTC, SamVerschueren commented on src/lib/utils/update.ts
> +	return [value];
Small nitpick comment :).

```suggestion
	if (value.$each) {
		if (!Array.isArray(value.$each)) {
			throw new Error('The value for $each should be an array.');
		}

		return value.$each;
	}

	return [value];
```

2020-10-28 07:27 UTC, SamVerschueren commented
Regarding the `$removeFromSet`, we might go with that one I guess. The `$pull` operator works quite differently because it accepts conditions which DynamoDB doesn't support either.

2020-10-28 11:41 UTC, onhate commented
@SamVerschueren good question, as per the documentation there are no sets of arrays, so I guess in this case we should treat it as `$each`, I did tests and it fails, pushed the fix, good catch!

```
Set collection types | SS (string set) type, NS (number set) type, or BS (binary set) type.
```

2020-10-28 15:00 UTC, SamVerschueren requested changes
Two small documentation comments but other than that, nice job!

2020-10-28 15:00 UTC, SamVerschueren commented on readme.md
> +		// => {FirstName: 'Foo', Name: 'Bar', Salary: 4650, Title: 'CTO', Organisation: 'Amazon', Email: 'foo.bar@amazon.com', Hobby: ['cycling', 'swimming', 'walking'], Departments: ['IT]}
```suggestion
		// => {FirstName: 'Foo', Name: 'Bar', Salary: 4650, Title: 'CTO', Organisation: 'Amazon', Email: 'foo.bar@amazon.com', Hobby: ['cycling', 'swimming', 'walking'], Departments: ['IT']}
```

2020-10-28 15:00 UTC, SamVerschueren commented on readme.md
> +		// => {FirstName: 'Foo', Name: 'Bar', Salary: 4650, Title: 'CTO', Organisation: 'Amazon', Email: 'foo.bar@amazon.com', Hobby: ['programming', 'cycling', 'swimming', 'walking'], Departments: ['IT]}
```suggestion
		// => {FirstName: 'Foo', Name: 'Bar', Salary: 4650, Title: 'CTO', Organisation: 'Amazon', Email: 'foo.bar@amazon.com', Hobby: ['programming', 'cycling', 'swimming', 'walking'], Departments: ['IT']}
```

2020-10-28 15:14 UTC, onhate commented
@SamVerschueren done

2020-10-29 16:40 UTC, SamVerschueren approved these changes

2020-10-29 16:42 UTC, merged

2020-10-29 16:43 UTC, SamVerschueren commented
Thank you!